### ISSUE TITLE
error when changing user data (password etc)

### ISSUE THREAD

**Issue by pasichnikroman** [MageMontreal/mailgun-magento2#2]
I got an error when I try to change admin user settings   
Magento 2.3.2
admin -> system -> permissions ->  all users ->  change any user data -> save

`Fatal error: Uncaught Error: Call to a member function getType() on boolean in vendor/magemontreal/mailgun-magento2/Mail/MessageParser.php:31 Stack trace: #0 /vendor/magemontreal/mailgun-magento2/Mail/Transport.php(79): MageMontreal\Mailgun\Mail\MessageParser->parse() #1 /vendor/magemontreal/mailgun-magento2/Mail/Transport.php(60): MageMontreal\Mailgun\Mail\Transport->parseMessage() #2 vendor/magento/framework/Interception/Interceptor.php(58): MageMontreal\Mailgun\Mail\Transport->sendMessage() #3 /vendor/magento/framework/Interception/Interceptor.php(138): MageMontreal\Mailgun\Mail\Transport\Interceptor->___callParent('sendMessage', Array) #4 /vendor/dotmailer/dotmailer-magento2-extension/Plugin/TransportPlugin.php(75): MageMontreal\Mailgun\Mail\Transport\Interceptor->Magento\Framework\Interception\{closure}() #5 /vendor/magento/framework/Interception/Interceptor.php(1 in /vendor/magemontreal/mailgun-magento2/Mail/MessageParser.php on line 31`

**Comment by nicolas-medina** [comment]
Hi @pasichnikroman,

Thanks for your report. This is fixed in version 1.0.1.
